# Generated by Django 5.2.16 on 2026-08-04 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retest_workflow', models.BooleanField(default=True, help_text='Retest/remediation tracking on findings (Fixed/Not Fixed/etc. + history).')),
                ('notifications', models.BooleanField(default=True, help_text='Reviewer/QA assignment notifications, both in-app and email. Per-user email opt-out (see accounts:notification_preferences) still applies on top of this.')),
                ('recurrence_and_trends', models.BooleanField(default=True, help_text='Recurring-vulnerability detection on the finding page, and the cross-engagement Trends page.')),
                ('cvss_calculator', models.BooleanField(default=True, help_text='CVSS v3.1/v4.0 calculator widget on the finding create/edit form.')),
                ('global_search', models.BooleanField(default=True, help_text='Global search across every engagement/finding the user has access to.')),
                ('scan_import', models.BooleanField(default=True, help_text='Scanner import (Nmap / Burp Suite / Nuclei) on the findings list.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_flag_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
