# Generated by Django 5.2.16 on 2026-08-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureflags',
            name='mfa_required',
            field=models.BooleanField(default=True, help_text='Require TOTP MFA for local accounts. Turning this OFF removes a real security control instance-wide — only do this for a disposable/private-network test instance, never production.'),
        ),
    ]
