# Generated by Django 5.2.16 on 2026-08-04 17:00

from django.db import migrations, models


def disable_mfa_requirement(apps, schema_editor):
    # Not just a schema default change for future rows — this project isn't
    # production-ready yet, so an already-provisioned instance's existing
    # FeatureFlags row (created back when the default was True) needs to
    # actually flip to match, not silently keep the old value forever.
    FeatureFlags = apps.get_model("feature_flags", "FeatureFlags")
    FeatureFlags.objects.update(mfa_required=False)


def reenable_mfa_requirement(apps, schema_editor):
    FeatureFlags = apps.get_model("feature_flags", "FeatureFlags")
    FeatureFlags.objects.update(mfa_required=True)


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flags', '0002_featureflags_mfa_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflags',
            name='mfa_required',
            field=models.BooleanField(default=False, help_text='Require TOTP MFA for local accounts. Turning this ON is the right call before any real deployment; leave it OFF for local/disposable dev and test instances.'),
        ),
        migrations.RunPython(disable_mfa_requirement, reenable_mfa_requirement),
    ]
