# Generated by Django 5.2.16 on 2026-08-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flags', '0003_alter_featureflags_mfa_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureflags',
            name='client_portal_enabled',
            field=models.BooleanField(default=False, help_text='Allow client-role accounts to log in and use the client portal. Managing Client companies/accounts stays available to Superadmin/Team Lead either way.'),
        ),
    ]
