# Generated by Django 5.2.16 on 2026-09-19 00:00

from django.db import migrations, models


def enable_mfa_requirement(apps, schema_editor):
    # Same reasoning as 0003 in reverse: a schema default change alone doesn't
    # touch an already-provisioned instance's existing FeatureFlags row, so
    # flip it explicitly rather than leaving already-deployed instances stuck
    # on the old, less-secure default forever.
    FeatureFlags = apps.get_model("feature_flags", "FeatureFlags")
    FeatureFlags.objects.update(mfa_required=True)


def disable_mfa_requirement(apps, schema_editor):
    FeatureFlags = apps.get_model("feature_flags", "FeatureFlags")
    FeatureFlags.objects.update(mfa_required=False)


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flags', '0004_featureflags_client_portal_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflags',
            name='mfa_required',
            field=models.BooleanField(default=True, help_text='Require TOTP MFA for local accounts. This is the right call before any real deployment; turn it OFF only for a local/disposable dev or test instance.'),
        ),
        migrations.RunPython(enable_mfa_requirement, disable_mfa_requirement),
    ]
