# Generated by Django 5.2.16 on 2026-08-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_checklist_templates_team_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='auth_method',
            field=models.CharField(choices=[('local', 'Local'), ('oauth', 'OAuth')], default='local', max_length=8),
        ),
    ]
