# Generated by Django 5.2.16 on 2026-09-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_engagements_release_to_client_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='qualifications',
            field=models.TextField(blank=True, default=''),
        ),
    ]
