# Generated by Django 5.2.17 on 2026-09-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oauth_invite_pending',
            field=models.BooleanField(default=False, help_text='True for an admin-pre-created OAuth account that has not yet been claimed by a matching first sign-in through the identity provider.'),
        ),
    ]
