# Generated by Django 5.2.16 on 2026-07-31 06:40

import apps.findings.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxonomy', models.CharField(choices=[('OWASP_TOP10', 'OWASP Top 10'), ('MITRE_ATTACK', 'MITRE ATT&CK'), ('MITRE_CWE', 'MITRE CWE')], max_length=16)),
                ('code', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['taxonomy', 'code'],
                'constraints': [models.UniqueConstraint(fields=('taxonomy', 'code'), name='unique_taxonomy_code')],
            },
        ),
        migrations.CreateModel(
            name='CommentThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(choices=[('vulnerability_description', 'vulnerability_description'), ('business_impact', 'business_impact'), ('testing_summary', 'testing_summary'), ('technical_details', 'technical_details'), ('recommendations', 'recommendations'), ('note', 'note')], max_length=32)),
                ('start_pos', models.PositiveIntegerField()),
                ('end_pos', models.PositiveIntegerField()),
                ('anchored_text_ciphertext', models.BinaryField()),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_threads_started', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['field_name', 'start_pos'],
            },
        ),
        migrations.CreateModel(
            name='CommentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_ciphertext', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_entries', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='findings.commentthread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('cvss_score', models.CharField(blank=True, default='', max_length=32)),
                ('cvss_vector', models.CharField(blank=True, default='', max_length=255, validators=[apps.findings.validators.validate_cvss_vector])),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFORMATIONAL', 'Informational')], max_length=16)),
                ('cve_id', models.CharField(blank=True, default='', max_length=32, validators=[apps.findings.validators.validate_cve_id])),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=16)),
                ('vulnerability_description', models.TextField(blank=True, default='')),
                ('business_impact', models.TextField(blank=True, default='')),
                ('testing_summary', models.TextField(blank=True, default='')),
                ('affects', models.TextField(blank=True, default='')),
                ('technical_details_ciphertext', models.BinaryField()),
                ('note_ciphertext', models.BinaryField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, default='')),
                ('references', models.TextField(blank=True, default='')),
                ('workflow_status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEWED', 'Reviewed'), ('REVIEW_CHANGES_REQUESTED', 'Changes Requested (Review)'), ('SELF_REVIEWED', 'Self-Reviewed — no peer QA'), ('QA_APPROVED', 'QA Approved'), ('QA_CHANGES_REQUESTED', 'Changes Requested (QA)')], default='DRAFT', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_qa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings_to_qa', to=settings.AUTH_USER_MODEL)),
                ('assigned_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings_to_review', to=settings.AUTH_USER_MODEL)),
                ('classifications', models.ManyToManyField(related_name='findings', to='findings.classificationtag')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings_created', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='engagements.engagement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='commentthread',
            name='finding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_threads', to='findings.finding'),
        ),
        migrations.CreateModel(
            name='VulnerabilityTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('default_severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFORMATIONAL', 'Informational')], max_length=16)),
                ('default_cvss_score', models.CharField(blank=True, default='', max_length=32)),
                ('default_cvss_vector', models.CharField(blank=True, default='', max_length=255, validators=[apps.findings.validators.validate_cvss_vector])),
                ('vulnerability_description', models.TextField(blank=True, default='')),
                ('business_impact', models.TextField(blank=True, default='')),
                ('testing_summary', models.TextField(blank=True, default='')),
                ('technical_details', models.TextField(blank=True, default='')),
                ('recommendations', models.TextField(blank=True, default='')),
                ('references', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classifications', models.ManyToManyField(related_name='vulnerability_templates', to='findings.classificationtag')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vulnerability_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
