# Generated by Django 5.2.16 on 2026-07-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0005_references_rich_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentthread',
            name='field_name',
            field=models.CharField(choices=[('vulnerability_description', 'vulnerability_description'), ('business_impact', 'business_impact'), ('testing_summary', 'testing_summary'), ('technical_details', 'technical_details'), ('recommendations', 'recommendations'), ('references', 'references'), ('note', 'note')], max_length=32),
        ),
    ]
