# Generated by Django 5.2.16 on 2026-08-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0011_finding_remediation_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='finding',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
