# Generated by Django 5.2.16 on 2026-08-04 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0012_finding_archived_finding_archived_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='retest_status',
            field=models.CharField(choices=[('NOT_RETESTED', 'Not Retested'), ('FIXED', 'Fixed'), ('NOT_FIXED', 'Not Fixed'), ('PARTIALLY_FIXED', 'Partially Fixed'), ('RISK_ACCEPTED', 'Risk Accepted')], default='NOT_RETESTED', max_length=32),
        ),
        migrations.CreateModel(
            name='RetestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_RETESTED', 'Not Retested'), ('FIXED', 'Fixed'), ('NOT_FIXED', 'Not Fixed'), ('PARTIALLY_FIXED', 'Partially Fixed'), ('RISK_ACCEPTED', 'Risk Accepted')], max_length=32)),
                ('notes_ciphertext', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retest_records', to='findings.finding')),
                ('tested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retest_records_logged', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
