# Generated by Django 5.2.16 on 2026-08-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0013_finding_retest_status_retestrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='display_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
