# Generated by Django 5.2.16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('findings', '0014_finding_display_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldVisibilitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_vulnerability_description', models.BooleanField(default=True, verbose_name='Vulnerability description')),
                ('finding_business_impact', models.BooleanField(default=True, verbose_name='Business impact')),
                ('finding_testing_summary', models.BooleanField(default=True, verbose_name='Testing summary')),
                ('finding_remediation_testing', models.BooleanField(default=True, verbose_name='Remediation testing')),
                ('finding_recommendations', models.BooleanField(default=True, verbose_name='Recommendations')),
                ('finding_references', models.BooleanField(default=True, verbose_name='References')),
                ('finding_note', models.BooleanField(default=True, verbose_name='Internal note')),
                ('template_vulnerability_description', models.BooleanField(default=True, verbose_name='Vulnerability description')),
                ('template_business_impact', models.BooleanField(default=True, verbose_name='Business impact')),
                ('template_testing_summary', models.BooleanField(default=True, verbose_name='Testing summary')),
                ('template_technical_details', models.BooleanField(default=True, verbose_name='Technical details')),
                ('template_recommendations', models.BooleanField(default=True, verbose_name='Recommendations')),
                ('template_references', models.BooleanField(default=True, verbose_name='References')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_visibility_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
