# Generated by Django 5.2.16 on 2026-09-05 04:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0016_alter_vulnerabilitytemplate_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finding',
            name='business_impact',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='note_ciphertext',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='recommendations',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='references',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='remediation_testing_ciphertext',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='technical_details_ciphertext',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='testing_summary',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='vulnerability_description',
        ),
        migrations.RemoveField(
            model_name='vulnerabilitytemplate',
            name='business_impact',
        ),
        migrations.RemoveField(
            model_name='vulnerabilitytemplate',
            name='recommendations',
        ),
        migrations.RemoveField(
            model_name='vulnerabilitytemplate',
            name='references',
        ),
        migrations.RemoveField(
            model_name='vulnerabilitytemplate',
            name='technical_details',
        ),
        migrations.RemoveField(
            model_name='vulnerabilitytemplate',
            name='testing_summary',
        ),
        migrations.RemoveField(
            model_name='vulnerabilitytemplate',
            name='vulnerability_description',
        ),
        migrations.AlterField(
            model_name='commentthread',
            name='field_name',
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name='ContentSectionDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('supports_image_upload', models.BooleanField(default=False)),
                ('portal_visible', models.BooleanField(default=False)),
                ('include_in_remediation_report_only', models.BooleanField(default=False)),
                ('is_import_target', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_section_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FindingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_ciphertext', models.BinaryField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finding_sections', to='findings.contentsectiondefinition')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='findings.finding')),
            ],
            options={
                'ordering': ['definition__order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_sections', to='findings.contentsectiondefinition')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='findings.vulnerabilitytemplate')),
            ],
            options={
                'ordering': ['definition__order'],
            },
        ),
        migrations.DeleteModel(
            name='FieldVisibilitySettings',
        ),
        migrations.AddConstraint(
            model_name='findingsection',
            constraint=models.UniqueConstraint(fields=('finding', 'definition'), name='unique_finding_section'),
        ),
        migrations.AddConstraint(
            model_name='templatesection',
            constraint=models.UniqueConstraint(fields=('template', 'definition'), name='unique_template_section'),
        ),
    ]
