# Generated by Django 5.2.17 on 2026-09-16 13:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0007_engagementstatushistory'),
        ('findings', '0019_vulnerabilitytemplateapprovedversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanImportRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_format', models.CharField(max_length=16)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('findings_created', models.PositiveIntegerField(default=0)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_imports', to='engagements.engagement')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['imported_at'],
            },
        ),
    ]
