# Generated by Django 5.2.16 on 2026-07-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='reference_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
