# Generated by Django 5.2.16 on 2026-08-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0002_engagement_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='test_type',
            field=models.CharField(blank=True, choices=[('WEB_APPLICATION', 'Web Application Penetration Test'), ('NETWORK', 'Network Penetration Test'), ('VULNERABILITY_SCAN', 'Vulnerability Scan')], default='', max_length=32),
        ),
    ]
