# Generated by Django 5.2.16 on 2026-08-27 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('engagements', '0003_engagement_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='clients.client'),
        ),
    ]
