# Generated by Django 5.2.16 on 2026-08-27 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0004_engagement_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='client_release_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engagement',
            name='client_release_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='client_release_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements_released', to=settings.AUTH_USER_MODEL),
        ),
    ]
