# Generated by Django 5.2.16 on 2026-09-03 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0006_engagement_default_approver_engagement_default_qa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('IN_REVIEW', 'In Review'), ('QA', 'QA'), ('APPROVED', 'Approved'), ('DELIVERED', 'Delivered'), ('AWAITING_REMEDIATION_TEST', 'Awaiting Remediation Test'), ('REMEDIATION_TEST', 'Remediation Test'), ('CLOSED', 'Closed')], max_length=32)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_status_changes', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='engagements.engagement')),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
    ]
