# Generated by Django 5.2.16 on 2026-07-31 06:40

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagements', '0001_initial'),
        ('findings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default='', max_length=32)),
                ('title', models.CharField(max_length=500)),
                ('reference_info', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('NOT_TESTED', 'Not Tested'), ('TESTED_NO_FINDING', 'Tested — No Finding'), ('TESTED_FINDING_RAISED', 'Tested — Finding Raised'), ('NOT_APPLICABLE', 'Not Applicable')], default='NOT_TESTED', max_length=32)),
                ('test_results_ciphertext', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='engagements.engagement')),
                ('findings', models.ManyToManyField(blank=True, related_name='checklist_items', to='findings.finding')),
            ],
            options={
                'ordering': ['order', 'category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItemComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body_ciphertext', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_comments', to=settings.AUTH_USER_MODEL)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='checklist.checklistitem')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_templates_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplateItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default='', max_length=32)),
                ('title', models.CharField(max_length=500)),
                ('reference_info', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklist.checklisttemplate')),
            ],
            options={
                'ordering': ['order', 'category', 'code'],
            },
        ),
    ]
