# Generated by Django 5.2.16 on 2026-08-26 10:28

import hashlib

from django.db import migrations, models

GENESIS_HASH = "0" * 64


def _compute_entry_hash(entry, prev_hash):
    # Deliberately duplicated from apps.audit.integrity.compute_entry_hash
    # rather than imported — this migration must keep producing the exact
    # same hashes it always has even if that function's logic ever
    # changes later, since a migration re-run (or a fresh `migrate` on an
    # old database) needs byte-for-byte identical output every time.
    canonical = "|".join(
        "" if value is None else str(value)
        for value in [
            prev_hash,
            entry.pk,
            entry.created_at.isoformat(),
            entry.actor_id,
            entry.actor_username,
            entry.actor_role,
            entry.action,
            entry.method,
            entry.path,
            entry.status_code,
            entry.engagement_id,
            entry.object_ref,
            entry.ip_address,
            entry.query_string,
            entry.referer,
            entry.user_agent,
            entry.duration_ms,
        ]
    )
    return hashlib.sha256(canonical.encode()).hexdigest()


def backfill_entry_hash(apps, schema_editor):
    # Rows created before hash-chaining existed have no entry_hash yet —
    # without this, `verify_audit_log` would treat every one of them as
    # tampered (a blank hash where a real one should be) the moment this
    # migration runs on an existing instance. Chains them retroactively,
    # in insertion (pk) order, exactly as apps.audit.integrity.
    # append_with_chain would have at the time each was created.
    AuditLogEntry = apps.get_model("audit", "AuditLogEntry")
    prev_hash = GENESIS_HASH
    for entry in AuditLogEntry.objects.order_by("pk").iterator():
        entry.entry_hash = _compute_entry_hash(entry, prev_hash)
        entry.save(update_fields=["entry_hash"])
        prev_hash = entry.entry_hash


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditlogentry_duration_ms_auditlogentry_query_string_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogentry',
            name='entry_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.RunPython(backfill_entry_hash, migrations.RunPython.noop),
    ]
