# Converts AuditLogEntry to a Postgres-native table partitioned by
# RANGE (created_at), one partition per calendar year, so that:
#   - apps.audit.retention can DROP/DETACH a whole expired year instead
#     of a row-by-row DELETE sweep once retention (6 years, currently
#     ~2190 days) starts actually expiring data;
#   - queries filtered by a time range (the dominant access pattern —
#     order_by("-created_at"), the admin's date_hierarchy) only scan
#     relevant partitions instead of the whole table as it grows.
#
# Postgres can't ALTER an existing heap table into a partitioned one —
# partitioning must be declared at CREATE TABLE time — so this drops and
# recreates the table. Done here as a straight drop/recreate (not a
# data-preserving copy) because this instance has no real production
# data yet (confirmed with the app owner — pre-release, dev environment,
# the ~11k existing rows are disposable test traffic). A later instance
# with real data to preserve would need an INSERT...SELECT copy step
# instead of TRUNCATE/DROP; that's deliberately not what this migration
# does.
#
# id stays a normal Django primary_key=True BigAutoField — no ORM/admin
# code needed to change. Postgres requires the partition column
# (created_at) in every UNIQUE/PRIMARY KEY constraint on a partitioned
# table; rather than making the table's actual PRIMARY KEY composite
# (which conflicts with Django's own AutoField validation and blocks
# admin registration entirely — see the model's docstring), that
# requirement is satisfied by a separate UNIQUE (id, created_at)
# constraint that is *not* the primary key. The table keeps a plain
# PRIMARY KEY-less id column (still unique via UNIQUE (id, created_at),
# still indexed on its own for lookups) exactly as Django expects it.
from django.conf import settings
from django.db import migrations

# Only 2026 has any data today (this app's whole lifetime so far).
# create_audit_partition (new management command, run yearly via cron
# the same way apps.audit.management.commands.purge_audit_log already
# documents its own cron line) creates each subsequent year ahead of
# time; 2027 is pre-created here so there's no gap immediately after
# this migration runs.
YEARS = [2026, 2027]

# DEFAULT catches any row whose created_at falls outside every declared
# partition (e.g. a missed yearly cron run, clock skew) — without it,
# an INSERT for an unrouted created_at would fail outright, and this
# table's writer (apps.audit.integrity.append_with_chain) must never
# fail to log an action just because a partition wasn't pre-created.
PARTITION_SQL = """
DROP TABLE IF EXISTS audit_auditlogentry CASCADE;

CREATE TABLE audit_auditlogentry (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    actor_id bigint REFERENCES accounts_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    actor_username varchar(150) NOT NULL,
    actor_role varchar(32) NOT NULL,
    action varchar(150) NOT NULL,
    method varchar(8) NOT NULL,
    path varchar(500) NOT NULL,
    status_code smallint NOT NULL CHECK (status_code >= 0),
    engagement_id varchar(64) NOT NULL,
    object_ref varchar(255) NOT NULL,
    ip_address inet,
    query_string varchar(500) NOT NULL,
    referer varchar(500) NOT NULL,
    user_agent varchar(300) NOT NULL,
    duration_ms integer CHECK (duration_ms >= 0),
    created_at timestamptz NOT NULL,
    entry_hash varchar(64) NOT NULL,
    UNIQUE (id, created_at)
) PARTITION BY RANGE (created_at);

CREATE TABLE audit_auditlogentry_default PARTITION OF audit_auditlogentry DEFAULT;

{year_partitions}

CREATE INDEX ON audit_auditlogentry (id);
CREATE INDEX ON audit_auditlogentry (created_at);
CREATE INDEX ON audit_auditlogentry (engagement_id);
CREATE INDEX ON audit_auditlogentry (engagement_id varchar_pattern_ops);
CREATE INDEX ON audit_auditlogentry (actor_id);
CREATE INDEX ON audit_auditlogentry (actor_id, created_at);
CREATE INDEX ON audit_auditlogentry (action, created_at);
CREATE INDEX ON audit_auditlogentry (engagement_id, created_at);

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX ON audit_auditlogentry USING GIN (actor_username gin_trgm_ops);
CREATE INDEX ON audit_auditlogentry USING GIN (action gin_trgm_ops);
CREATE INDEX ON audit_auditlogentry USING GIN (path gin_trgm_ops);
CREATE INDEX ON audit_auditlogentry USING GIN (object_ref gin_trgm_ops);
CREATE INDEX ON audit_auditlogentry USING GIN ((ip_address::text) gin_trgm_ops);
CREATE INDEX ON audit_auditlogentry USING GIN (user_agent gin_trgm_ops);
CREATE INDEX ON audit_auditlogentry USING GIN (referer gin_trgm_ops);
CREATE INDEX ON audit_auditlogentry USING GIN (engagement_id gin_trgm_ops);
""".format(
    year_partitions="\n".join(
        f"CREATE TABLE audit_auditlogentry_{year} PARTITION OF audit_auditlogentry "
        f"FOR VALUES FROM ('{year}-01-01') TO ('{year + 1}-01-01');"
        for year in YEARS
    )
)


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_pg_trgm_search_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql=PARTITION_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
