# Generated by Django 5.2.16 on 2026-07-31 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_title', models.CharField(blank=True, default='Penetration Test Report', max_length=255)),
                ('front_matter', models.TextField(blank=True, default='')),
                ('back_matter', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
