# Generated by Django 5.2.16 on 2026-08-08 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0003_engagement_test_type'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsettings',
            name='classification_label',
            field=models.CharField(blank=True, default='Strictly Confidential', max_length=64),
        ),
        migrations.AddField(
            model_name='reportsettings',
            name='dynamic_defaults',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reportsettings',
            name='finding_id_prefix',
            field=models.CharField(blank=True, default='F', max_length=16),
        ),
        migrations.AddField(
            model_name='reportsettings',
            name='severity_colors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ReportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('is_template', models.BooleanField(default=False)),
                ('is_remediation_report', models.BooleanField(default=False)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_configs_created', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_configs', to='engagements.engagement')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
