# Generated by Django 5.2.16 on 2026-08-08 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0003_engagement_test_type'),
        ('reports', '0002_reportsettings_classification_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsettings',
            name='max_concurrent_report_jobs',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.CreateModel(
            name='ReportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fmt', models.CharField(max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='engagements.engagement')),
            ],
        ),
    ]
