# Generated by Django 5.2.16 on 2026-08-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportsettings_max_concurrent_report_jobs_reportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsettings',
            name='body_font',
            field=models.CharField(blank=True, default='Helvetica', max_length=100),
        ),
        migrations.AddField(
            model_name='reportsettings',
            name='bullet_character',
            field=models.CharField(blank=True, default='•', max_length=8),
        ),
        migrations.AddField(
            model_name='reportsettings',
            name='monospace_font',
            field=models.CharField(blank=True, default='Courier New', max_length=100),
        ),
    ]
