# Generated by Django 5.2.16 on 2026-08-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_reportsettings_body_font_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedGoogleFont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=100)),
                ('weight', models.CharField(default='400', max_length=8)),
                ('style', models.CharField(default='normal', max_length=16)),
                ('font_format', models.CharField(default='woff2', max_length=16)),
                ('content_type', models.CharField(default='font/woff2', max_length=64)),
                ('font_data', models.BinaryField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('family', 'weight', 'style'), name='unique_cached_google_font_variant')],
            },
        ),
    ]
