# Generated by Django 5.2.16 on 2026-08-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_cachedgooglefont'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsettings',
            name='table_header_color',
            field=models.CharField(blank=True, default='rgba(248,250,252,1)', max_length=64),
        ),
    ]
