# Generated by Django 5.2.16 on 2026-08-27 14:53

import apps.reports.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_reportsettings_table_header_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsettings',
            name='body_font',
            field=models.CharField(blank=True, default='Helvetica', max_length=100, validators=[apps.reports.validators.validate_font_name]),
        ),
        migrations.AlterField(
            model_name='reportsettings',
            name='bullet_character',
            field=models.CharField(blank=True, default='•', max_length=8, validators=[apps.reports.validators.validate_no_markup_chars]),
        ),
        migrations.AlterField(
            model_name='reportsettings',
            name='monospace_font',
            field=models.CharField(blank=True, default='Courier New', max_length=100, validators=[apps.reports.validators.validate_font_name]),
        ),
        migrations.AlterField(
            model_name='reportsettings',
            name='table_header_color',
            field=models.CharField(blank=True, default='rgba(248,250,252,1)', max_length=64, validators=[apps.reports.validators.validate_rgba]),
        ),
    ]
