# Generated by Django 5.2.16 on 2026-08-28 17:09

import apps.reports.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_reportsettings_body_font_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsettings',
            name='body_font',
            field=models.CharField(blank=True, default='Open Sans', max_length=100, validators=[apps.reports.validators.validate_font_name]),
        ),
        migrations.AlterField(
            model_name='reportsettings',
            name='monospace_font',
            field=models.CharField(blank=True, default='JetBrains Mono', max_length=100, validators=[apps.reports.validators.validate_font_name]),
        ),
    ]
