# Generated by Django 5.2.16 on 2026-08-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_reportsettings_body_font_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsettings',
            name='firm_logo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportsettings',
            name='firm_logo_content_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='reportsettings',
            name='firm_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
