# Generated by Django 5.2.16 on 2026-09-03 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0007_engagementstatushistory'),
        ('reports', '0010_reportexportlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reportconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_template', False)), fields=('engagement',), name='unique_draft_reportconfig_per_engagement'),
        ),
    ]
