# Generated by Django 5.2.16 on 2026-09-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_shared_text_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportprofile',
            name='docx_template',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportprofile',
            name='docx_template_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
