# Generated by Django 5.2.16 on 2026-09-08 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_reportprofile_docx_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportprofile',
            name='docx_template',
        ),
        migrations.RemoveField(
            model_name='reportprofile',
            name='docx_template_filename',
        ),
    ]
