# Generated by Django 5.2.16 on 2026-09-09 06:19

import apps.reports.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_front_matter_layout_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportprofile',
            name='empty_cell_background_color',
            field=models.CharField(blank=True, default='rgba(237,238,238,1)', help_text='Used for a severity/status table cell whose color field below is left blank.', max_length=64, validators=[apps.reports.validators.validate_rgba]),
        ),
    ]
