# Generated by Django 5.2.16 on 2026-09-09 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_fold_shared_text_blocks_into_profiles'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reporttextblockdefinition',
            name='unique_shared_text_block_slug',
        ),
        migrations.RemoveField(
            model_name='reporttextblockdefinition',
            name='content',
        ),
        migrations.AlterField(
            model_name='reporttextblockdefinition',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_blocks', to='reports.reportprofile'),
        ),
    ]
