# Generated by Django 5.2.16 on 2026-09-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_simplify_text_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportprofile',
            name='labels',
            field=models.JSONField(blank=True, default=dict, help_text='Overrides for field/column label text baked into the report — see reports.labels.LABEL_DEFAULTS. A missing or blank key falls back to the shipped English default.'),
        ),
    ]
