# Generated by Django 5.2.17 on 2026-09-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0026_seed_default_report_fonts'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportprofile',
            name='docx_style_map',
            field=models.JSONField(blank=True, default=dict, help_text="Maps each DOCX content role (see reports.docx_style_roles.STYLE_ROLES) to a style name from the uploaded template's own style catalog."),
        ),
        migrations.AddField(
            model_name='reportprofile',
            name='docx_template',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportprofile',
            name='docx_template_content_type',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='reportprofile',
            name='docx_template_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reportprofile',
            name='docx_template_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
