# Generated by Django 5.2.16 on 2026-08-28 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0005_engagement_client_release_approved_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='engagements.engagement'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('REVIEWER_ASSIGNED', 'Assigned as reviewer'), ('QA_ASSIGNED', 'Assigned as QA approver'), ('SCOPE_CHANGE_APPROVED', 'Scope change approved'), ('SCOPE_CHANGE_REJECTED', 'Scope change rejected')], max_length=32),
        ),
    ]
