# Generated by Django 5.2.16 on 2026-09-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_engagement_alter_notification_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('REVIEWER_ASSIGNED', 'Assigned as reviewer'), ('QA_ASSIGNED', 'Assigned as QA approver'), ('SCOPE_CHANGE_APPROVED', 'Scope change approved'), ('SCOPE_CHANGE_REJECTED', 'Scope change rejected'), ('APPROVAL_READY', 'Engagement ready for approval')], max_length=32),
        ),
    ]
