# Generated by Django 5.2.17 on 2026-09-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('REVIEWER_ASSIGNED', 'Assigned as reviewer'), ('QA_ASSIGNED', 'Assigned as QA approver'), ('SCOPE_CHANGE_APPROVED', 'Scope change approved'), ('SCOPE_CHANGE_REJECTED', 'Scope change rejected'), ('APPROVAL_READY', 'Engagement ready for approval'), ('REVIEWED', 'Finding reviewed'), ('REVIEW_CHANGES_REQUESTED', 'Review changes requested'), ('QA_APPROVED', 'Finding QA approved'), ('QA_CHANGES_REQUESTED', 'QA changes requested')], max_length=32),
        ),
    ]
